VERSION: "1.0.0" # Internal use only

entities:
  # Enable or disable vanilla entity registration
  register: true
  # Enable lightning and fire damage
  lightning-fire-damage: true
  # Enable or disable minecart functionality
  minecarts: true
  # Enable or disable fireworks
  fireworks: true
  end-crystal:
    # Enable or disable End Crystal explosions
    explosions: true
    # Set End Crystal explosion power
    power: 6
  creeper:
    # Enable or disable creeper explosions
    explosions: false
    # Enable or disable charged creeper creation
    charged: true
    # Enable or disable the ability to use flint and steel to ignite creepers
    ignite: true
  golem:
    # Iron golem configuration
    iron:
      # Enable or disable iron golem functionality
      enabled: true
    # Snow golem configuration
    snow:
      # Enable or disable snow golem functionality
      enabled: true
      # Enable or disable snow golem ability for leaving snow trails
      snow-generation: false
      # Enable or disable snow golem melting when in hot biomes
      melting: true
  xp:
    # Enable or disable mob XP drops
    mob-xp: true

enchantments:
  # Enable or disable vanilla enchantment registration
  vanilla: true
  # Enable or disable enchantment tables
  # WARNING: This feature is currently handled by the client and can be exploited
  enchantment-table: true

dimensions:
  # Nether dimension configuration
  nether:
    # Enable or disable the Nether dimension
    enabled: true
    # Set the name of the nether level
    name: "nether"
    # Enable or disable the ability to teleport to the nether like vanilla
    vanilla-teleport: false
  # End dimension configuration
  end:
    # Enable or disable the End dimension
    enabled: true
    # Set the name of the end level
    name: "end"

weather:
  # Enable or disable the weather cycle
  enabled: true
  # These values are in ticks
  duration:
    # Minimum weather duration for one cycle
    minimum: 6000
    # Maximum weather duration for one cycle
    maximum: 12000
  # Enable or disable lightning in weather storms
  lightning: true

player:
  # Choose whether to limit players in creative from moving or dropping items
  limited-creative: false
  # Choose whether to clear a player's inventory when they switch gamemodes
  clear-inv: false
  # Instant armor equip configuration
  instant-armor:
    # Choose whether to allow players to right click armor to equip
    enabled: true
    # Enable or disable the ability to replace current armor
    replace: false
  # Elytra configuration
  elytra:
    # Enable or disable elytra functionality
    enabled: true
    # Enable or disable elytra boosting functionality
    boost: true
    # Enable or disable elytra particles
    particles: true
  # Enable or disable fishing functionality
  fishing: true

blocks:
  spawners:
    # Enable or disable mob spawner functionality
    enabled: true
    # Enable or disable the ability to drop spawners using silk touch
    silk-touch: false
  # Enable or disable dragon egg teleportation
  dragon-egg-teleport: true
  # Enable or disable brewing stand functionality
  brewing-stands: true
  # Enable or disable cauldron functionality
  cauldrons: true
  # Enable or disable shulker box functionality
  shulker-box: true
  # Enable or disable snow melting
  snow-melts: true
  # Enable or disable hopper functionality
  hoppers: true
  # Enable or disable anvil functionality
  # WARNING: This feature is currently handled by the client and can be exploited
  anvils: true
  beacons:
    # Enable or disable beacon functionality
    enabled: true
    # Enable or disable beacon effects
    effects: true